# Generated by Django 3.1.3 on 2021-05-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_sender', models.CharField(max_length=20)),
                ('email_of_sender', models.EmailField(max_length=254)),
                ('message_of_sender', models.TextField()),
            ],
        ),
    ]
