# Generated by Django 3.1.3 on 2021-05-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registered_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('gender', models.BooleanField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.IntegerField(max_length=11)),
                ('security_question', models.CharField(max_length=30)),
                ('answer', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=13)),
            ],
        ),
        migrations.AlterField(
            model_name='contact_model',
            name='message_of_sender',
            field=models.TextField(max_length=200),
        ),
    ]
