# Generated by Django 3.1.3 on 2021-05-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0003_auto_20210504_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered_users',
            old_name='user_email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='registered_users',
            name='answer',
            field=models.CharField(max_length=20),
        ),
    ]
